### ISSUE TITLE
Unusual 'offset is out of bounds' error (possible backend bug)

### ISSUE THREAD

**Issue by t1lde** [Plutonomicon/cardano-transaction-lib#1002]
Exception occurring when submitting a transaction as part of a long-running bot process:

```
[DEBUG] 2022-09-03T21:33:45.891Z sending: {"args":{"hash":"1e5594a47f6928634db1f4dc208e05d262b606933e97e3e44fcbcca48a08ceec"},"methodname":"GetDatumByHash","mirror":"GetDatumByHash-2ri0ovgaxgl7mf9pur","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}
[DEBUG] 2022-09-03T21:33:45.893Z message: {"reflection":"GetDatumByHash-2ri0ovgaxgl7mf9pur","methodname":"GetDatumByHash","result":{"DatumFound":{"value":[[10000000000000000,300000,0,3000000],[[[0,1],[4,5]],[["",""],["315b751adb64f3b1c3bb769440f19ad1c9d8ac4d2c4c42931900592f",""]],3,[1,1],[[1,20],[53,200],[697,200],[4,5]],2000000,{"constr":0,"fields":[{"constr":1,"fields":["8a9675abbd5ff0a4fa7b99ef73950d6a42f5c812b72a989e2acddee2"]},{"constr":1,"fields":[]}]}],1662240393000,[246385363,11221367219],[0,0,0,0],55328356]}},"version":"1.0","servicename":"ogmios-datum-cache","type":"jsonwsp/response"}
[DEBUG] 2022-09-03T21:33:45.966Z sending: {"args":{"hash":"1e5594a47f6928634db1f4dc208e05d262b606933e97e3e44fcbcca48a08ceec"},"methodname":"GetDatumByHash","mirror":"GetDatumByHash-2ri0ovgaxgl7mf9pwu","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}
[DEBUG] 2022-09-03T21:33:45.967Z message: {"reflection":"GetDatumByHash-2ri0ovgaxgl7mf9pwu","methodname":"GetDatumByHash","result":{"DatumFound":{"value":[[10000000000000000,300000,0,3000000],[[[0,1],[4,5]],[["",""],["315b751adb64f3b1c3bb769440f19ad1c9d8ac4d2c4c42931900592f",""]],3,[1,1],[[1,20],[53,200],[697,200],[4,5]],2000000,{"constr":0,"fields":[{"constr":1,"fields":["8a9675abbd5ff0a4fa7b99ef73950d6a42f5c812b72a989e2acddee2"]},{"constr":1,"fields":[]}]}],1662240393000,[246385363,11221367219],[0,0,0,0],55328356]}},"version":"1.0","servicename":"ogmios-datum-cache","type":"jsonwsp/response"}
[ERROR] 2022-09-03T21:33:46.017Z Error when executing contract: RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at passArray8ToWasm0 (/home/ubuntu/liqwid-offchain/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:189:23)
    at Function.new_bytes (/home/ubuntu/liqwid-offchain/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:6515:20)
    at Object.exports._mkPlutusData_bytes (/home/ubuntu/liqwid-offchain/cli.js:24476:57)
    at convertPlutusData (/home/ubuntu/liqwid-offchain/cli.js:24559:103)
    at go (/home/ubuntu/liqwid-offchain/cli.js:4790:44)
    at /home/ubuntu/liqwid-offchain/cli.js:4800:22
    at /home/ubuntu/liqwid-offchain/cli.js:4881:71
    at /home/ubuntu/liqwid-offchain/cli.js:24565:435
    at convertPlutusData (/home/ubuntu/liqwid-offchain/cli.js:24547:41)
[INFO] 2022-09-03T21:33:46.018Z Retrying..
[DEBUG] 2022-09-03T21:33:46.019Z sending: {"args":{"query":{"utxo":["\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"]}},"methodname":"Query","mirror":"Query-2ri0ovgaxgl7mf9pya","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}
[DEBUG] 2022-09-03T21:33:46.020Z message: {"type":"jsonwsp/fault","version":"1.0","servicename":"ogmios","fault":{"code":"client","string":"Invalid request: invalid query."},"reflection":"Query-2ri0ovgaxgl7mf9pya"}
```

When restarting the process, the same exception did not occur. This, plus the unusual value of 'utxo' shown in the logs makes me think this is an edge-case in CTL or upstream.

CC: @weskinner if he happens to have any more info (I think this is all we know though, unfortunately)

**Comment by klntsky** [comment]
The error message looks different, but the fact it comes from CSL AND happens after a while suggests that it may be another variant of https://github.com/Plutonomicon/cardano-transaction-lib/issues/875

**Comment by t1lde** [comment]
Another occurrence:

```
[ERROR] 2022-09-07T10:13:09.255Z Error when executing contract: Error: (AtKey "costModels" (AtKey "plutus:v1" (AtKey "addInteger-cpu-arguments-intercept" (TypeMismatch "Int"))))
    at Object.exports.error (/home/ubuntu/liqwid-offchain/cli.js:5339:12)
    at dispatchErrorToError (/home/ubuntu/liqwid-offchain/cli.js:27100:35)
    at /home/ubuntu/liqwid-offchain/cli.js:6032:51
    at __do (/home/ubuntu/liqwid-offchain/cli.js:27127:132)
    at __do (/home/ubuntu/liqwid-offchain/cli.js:27297:80)
    at func (/home/ubuntu/liqwid-offchain/cli.js:22820:14)
    at ReconnectingWebSocket._callEventListener (/home/ubuntu/liqwid-offchain/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:557:13)
    at /home/ubuntu/liqwid-offchain/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:81
    at Array.forEach (<anonymous>)
    at NoPerMessageDeflateWebSocket.ReconnectingWebSocket._handleMessage (/home/ubuntu/liqwid-offchain/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:38)
[INFO] 2022-09-07T10:13:09.255Z Retrying..
[DEBUG] 2022-09-07T10:13:09.256Z sending: {"args":{"query":{"utxo":["\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"]}},"methodname":"Query","mirror":"Query-2nsxctnl7rgpurs","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}
[DEBUG] 2022-09-07T10:13:09.257Z message: {"type":"jsonwsp/fault","version":"1.0","servicename":"ogmios","fault":{"code":"client","string":"Invalid request: invalid query."},"reflection":"Query-2nsxctnl7rgpurs"}
```

**Comment by klntsky** [comment]
@t1lde could you please post the ogmios response (a few lines above)

**Comment by klntsky** [comment]
> [DEBUG] 2022-09-07T10:13:09.256Z sending: {"args":{"query":{"utxo":["\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"]}},"methodname":"Query","mirror":"Query-2nsxctnl7rgpurs","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}


This is also very strange. Which revision are you on?

**Comment by t1lde** [comment]
> > [DEBUG] 2022-09-07T10:13:09.256Z sending: {"args":{"query":{"utxo":["\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"]}},"methodname":"Query","mirror":"Query-2nsxctnl7rgpurs","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}
> 
> This is also very strange. Which revision are you on?

ctl version: e637c9777c272f327a5ee8ade6d66ac435c71cc6 

> could you please post the ogmios response (a few lines above)

@weskinner may have more info

**Comment by t1lde** [comment]
> @t1lde could you please post the ogmios response (a few lines above)

```
sending: {"args":{"query":"currentProtocolParameters"},"methodname":"Query","mirror":"Query-2nsxctnl7rgpuax","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}
[DEBUG] 2022-09-07T10:13:08.681Z message: {"type":"jsonwsp/response","version":"1.0","servicename":"ogmios","methodname":"Query","result":{"minFeeCoefficient":44,"minFeeConstant":155381,"maxBlockBodySize":98304,"maxBlockHeaderSize":1100,"maxTxSize":16384,"stakeKeyDeposit":2000000,"poolDeposit":500000000,"poolRetirementEpochBound":18,"desiredNumberOfPools":500,"poolInfluence":"3/10","monetaryExpansion":"3/1000","treasuryExpansion":"1/5","protocolVersion":{"major":7,"minor":0},"minPoolCost":340000000,"coinsPerUtxoByte":4310,"costModels":{"plutus:v1":{"addInteger-cpu-arguments-intercept":205665,"addInteger-cpu-arguments-slope":812,"addInteger-memory-arguments-intercept":1,"addInteger-memory-arguments-slope":1,"appendByteString-cpu-arguments-intercept":1000,"appendByteString-cpu-arguments-slope":571,"appendByteString-memory-arguments-intercept":0,"appendByteString-memory-arguments-slope":1,"appendString-cpu-arguments-intercept":1000,"appendString-cpu-arguments-slope":24177,"appendString-memory-arguments-intercept":4,"appendString-memory-arguments-slope":1,"bData-cpu-arguments":1000,"bData-memory-arguments":32,"blake2b_256-cpu-arguments-intercept":117366,"blake2b_256-cpu-arguments-slope":10475,"blake2b_256-memory-arguments":4,"cekApplyCost-exBudgetCPU":23000,"cekApplyCost-exBudgetMemory":100,"cekBuiltinCost-exBudgetCPU":23000,"cekBuiltinCost-exBudgetMemory":100,"cekConstCost-exBudgetCPU":23000,"cekConstCost-exBudgetMemory":100,"cekDelayCost-exBudgetCPU":23000,"cekDelayCost-exBudgetMemory":100,"cekForceCost-exBudgetCPU":23000,"cekForceCost-exBudgetMemory":100,"cekLamCost-exBudgetCPU":23000,"cekLamCost-exBudgetMemory":100,"cekStartupCost-exBudgetCPU":100,"cekStartupCost-exBudgetMemory":100,"cekVarCost-exBudgetCPU":23000,"cekVarCost-exBudgetMemory":100,"chooseData-cpu-arguments":19537,"chooseData-memory-arguments":32,"chooseList-cpu-arguments":175354,"chooseList-memory-arguments":32,"chooseUnit-cpu-arguments":46417,"chooseUnit-memory-arguments":4,"consByteString-cpu-arguments-intercept":221973,"consByteString-cpu-arguments-slope":511,"consByteString-memory-arguments-intercept":0,"consByteString-memory-arguments-slope":1,"constrData-cpu-arguments":89141,"constrData-memory-arguments":32,"decodeUtf8-cpu-arguments-intercept":497525,"decodeUtf8-cpu-arguments-slope":14068,"decodeUtf8-memory-arguments-intercept":4,"decodeUtf8-memory-arguments-slope":2,"divideInteger-cpu-arguments-constant":196500,"divideInteger-cpu-arguments-model-arguments-intercept":453240,"divideInteger-cpu-arguments-model-arguments-slope":220,"divideInteger-memory-arguments-intercept":0,"divideInteger-memory-arguments-minimum":1,"divideInteger-memory-arguments-slope":1,"encodeUtf8-cpu-arguments-intercept":1000,"encodeUtf8-cpu-arguments-slope":28662,"encodeUtf8-memory-arguments-intercept":4,"encodeUtf8-memory-arguments-slope":2,"equalsByteString-cpu-arguments-constant":245000,"equalsByteString-cpu-arguments-intercept":216773,"equalsByteString-cpu-arguments-slope":62,"equalsByteString-memory-arguments":1,"equalsData-cpu-arguments-intercept":1060367,"equalsData-cpu-arguments-slope":12586,"equalsData-memory-arguments":1,"equalsInteger-cpu-arguments-intercept":208512,"equalsInteger-cpu-arguments-slope":421,"equalsInteger-memory-arguments":1,"equalsString-cpu-arguments-constant":187000,"equalsString-cpu-arguments-intercept":1000,"equalsString-cpu-arguments-slope":52998,"equalsString-memory-arguments":1,"fstPair-cpu-arguments":80436,"fstPair-memory-arguments":32,"headList-cpu-arguments":43249,"headList-memory-arguments":32,"iData-cpu-arguments":1000,"iData-memory-arguments":32,"ifThenElse-cpu-arguments":80556,"ifThenElse-memory-arguments":1,"indexByteString-cpu-arguments":57667,"indexByteString-memory-arguments":4,"lengthOfByteString-cpu-arguments":1000,"lengthOfByteString-memory-arguments":10,"lessThanByteString-cpu-arguments-intercept":197145,"lessThanByteString-cpu-arguments-slope":156,"lessThanByteString-memory-arguments":1,"lessThanEqualsByteString-cpu-arguments-intercept":197145,"lessThanEqualsByteString-cpu-arguments-slope":156,"lessThanEqualsByteString-memory-arguments":1,"lessThanEqualsInteger-cpu-arguments-intercept":204924,"lessThanEqualsInteger-cpu-arguments-slope":473,"lessThanEqualsInteger-memory-arguments":1,"lessThanInteger-cpu-arguments-intercept":208896,"lessThanInteger-cpu-arguments-slope":511,"lessThanInteger-memory-arguments":1,"listData-cpu-arguments":52467,"listData-memory-arguments":32,"mapData-cpu-arguments":64832,"mapData-memory-arguments":32,"mkCons-cpu-arguments":65493,"mkCons-memory-arguments":32,"mkNilData-cpu-arguments":22558,"mkNilData-memory-arguments":32,"mkNilPairData-cpu-arguments":16563,"mkNilPairData-memory-arguments":32,"mkPairData-cpu-arguments":76511,"mkPairData-memory-arguments":32,"modInteger-cpu-arguments-constant":196500,"modInteger-cpu-arguments-model-arguments-intercept":453240,"modInteger-cpu-arguments-model-arguments-slope":220,"modInteger-memory-arguments-intercept":0,"modInteger-memory-arguments-minimum":1,"modInteger-memory-arguments-slope":1,"multiplyInteger-cpu-arguments-intercept":69522,"multiplyInteger-cpu-arguments-slope":11687,"multiplyInteger-memory-arguments-intercept":0,"multiplyInteger-memory-arguments-slope":1,"nullList-cpu-arguments":60091,"nullList-memory-arguments":32,"quotientInteger-cpu-arguments-constant":196500,"quotientInteger-cpu-arguments-model-arguments-intercept":453240,"quotientInteger-cpu-arguments-model-arguments-slope":220,"quotientInteger-memory-arguments-intercept":0,"quotientInteger-memory-arguments-minimum":1,"quotientInteger-memory-arguments-slope":1,"remainderInteger-cpu-arguments-constant":196500,"remainderInteger-cpu-arguments-model-arguments-intercept":453240,"remainderInteger-cpu-arguments-model-arguments-slope":220,"remainderInteger-memory-arguments-intercept":0,"remainderInteger-memory-arguments-minimum":1,"remainderInteger-memory-arguments-slope":1,"sha2_256-cpu-arguments-intercept":806990,"sha2_256-cpu-arguments-slope":30482,"sha2_256-memory-arguments":4,"sha3_256-cpu-arguments-intercept":1927926,"sha3_256-cpu-arguments-slope":82523,"sha3_256-memory-arguments":4,"sliceByteString-cpu-arguments-intercept":265318,"sliceByteString-cpu-arguments-slope":0,"sliceByteString-memory-arguments-intercept":4,"sliceByteString-memory-arguments-slope":0,"sndPair-cpu-arguments":85931,"sndPair-memory-arguments":32,"subtractInteger-cpu-arguments-intercept":205665,"subtractInteger-cpu-arguments-slope":812,"subtractInteger-memory-arguments-intercept":1,"subtractInteger-memory-arguments-slope":1,"tailList-cpu-arguments":41182,"tailList-memory-arguments":32,"trace-cpu-arguments":212342,"trace-memory-arguments":32,"unBData-cpu-arguments":31220,"unBData-memory-arguments":32,"unConstrData-cpu-arguments":32696,"unConstrData-memory-arguments":32,"unIData-cpu-arguments":43357,"unIData-memory-arguments":32,"unListData-cpu-arguments":32247,"unListData-memory-arguments":32,"unMapData-cpu-arguments":38314,"unMapData-memory-arguments":32,"verifyEd25519Signature-cpu-arguments-intercept":9462713,"verifyEd25519Signature-cpu-arguments-slope":1021,"verifyEd25519Signature-memory-arguments":10},"plutus:v2":{"addInteger-cpu-arguments-intercept":205665,"addInteger-cpu-arguments-slope":812,"addInteger-memory-arguments-intercept":1,"addInteger-memory-arguments-slope":1,"appendByteString-cpu-arguments-intercept":1000,"appendByteString-cpu-arguments-slope":571,"appendByteString-memory-arguments-intercept":0,"appendByteString-memory-arguments-slope":1,"appendString-cpu-arguments-intercept":1000,"appendString-cpu-arguments-slope":24177,"appendString-memory-arguments-intercept":4,"appendString-memory-arguments-slope":1,"bData-cpu-arguments":1000,"bData-memory-arguments":32,"blake2b_256-cpu-arguments-intercept":117366,"blake2b_256-cpu-arguments-slope":10475,"blake2b_256-memory-arguments":4,"cekApplyCost-exBudgetCPU":23000,"cekApplyCost-exBudgetMemory":100,"cekBuiltinCost-exBudgetCPU":23000,"cekBuiltinCost-exBudgetMemory":100,"cekConstCost-exBudgetCPU":23000,"cekConstCost-exBudgetMemory":100,"cekDelayCost-exBudgetCPU":23000,"cekDelayCost-exBudgetMemory":100,"cekForceCost-exBudgetCPU":23000,"cekForceCost-exBudgetMemory":100,"cekLamCost-exBudgetCPU":23000,"cekLamCost-exBudgetMemory":100,"cekStartupCost-exBudgetCPU":100,"cekStartupCost-exBudgetMemory":100,"cekVarCost-exBudgetCPU":23000,"cekVarCost-exBudgetMemory":100,"chooseData-cpu-arguments":19537,"chooseData-memory-arguments":32,"chooseList-cpu-arguments":175354,"chooseList-memory-arguments":32,"chooseUnit-cpu-arguments":46417,"chooseUnit-memory-arguments":4,"consByteString-cpu-arguments-intercept":221973,"consByteString-cpu-arguments-slope":511,"consByteString-memory-arguments-intercept":0,"consByteString-memory-arguments-slope":1,"constrData-cpu-arguments":89141,"constrData-memory-arguments":32,"decodeUtf8-cpu-arguments-intercept":497525,"decodeUtf8-cpu-arguments-slope":14068,"decodeUtf8-memory-arguments-intercept":4,"decodeUtf8-memory-arguments-slope":2,"divideInteger-cpu-arguments-constant":196500,"divideInteger-cpu-arguments-model-arguments-intercept":453240,"divideInteger-cpu-arguments-model-arguments-slope":220,"divideInteger-memory-arguments-intercept":0,"divideInteger-memory-arguments-minimum":1,"divideInteger-memory-arguments-slope":1,"encodeUtf8-cpu-arguments-intercept":1000,"encodeUtf8-cpu-arguments-slope":28662,"encodeUtf8-memory-arguments-intercept":4,"encodeUtf8-memory-arguments-slope":2,"equalsByteString-cpu-arguments-constant":245000,"equalsByteString-cpu-arguments-intercept":216773,"equalsByteString-cpu-arguments-slope":62,"equalsByteString-memory-arguments":1,"equalsData-cpu-arguments-intercept":1060367,"equalsData-cpu-arguments-slope":12586,"equalsData-memory-arguments":1,"equalsInteger-cpu-arguments-intercept":208512,"equalsInteger-cpu-arguments-slope":421,"equalsInteger-memory-arguments":1,"equalsString-cpu-arguments-constant":187000,"equalsString-cpu-arguments-intercept":1000,"equalsString-cpu-arguments-slope":52998,"equalsString-memory-arguments":1,"fstPair-cpu-arguments":80436,"fstPair-memory-arguments":32,"headList-cpu-arguments":43249,"headList-memory-arguments":32,"iData-cpu-arguments":1000,"iData-memory-arguments":32,"ifThenElse-cpu-arguments":80556,"ifThenElse-memory-arguments":1,"indexByteString-cpu-arguments":57667,"indexByteString-memory-arguments":4,"lengthOfByteString-cpu-arguments":1000,"lengthOfByteString-memory-arguments":10,"lessThanByteString-cpu-arguments-intercept":197145,"lessThanByteString-cpu-arguments-slope":156,"lessThanByteString-memory-arguments":1,"lessThanEqualsByteString-cpu-arguments-intercept":197145,"lessThanEqualsByteString-cpu-arguments-slope":156,"lessThanEqualsByteString-memory-arguments":1,"lessThanEqualsInteger-cpu-arguments-intercept":204924,"lessThanEqualsInteger-cpu-arguments-slope":473,"lessThanEqualsInteger-memory-arguments":1,"lessThanInteger-cpu-arguments-intercept":208896,"lessThanInteger-cpu-arguments-slope":511,"lessThanInteger-memory-arguments":1,"listData-cpu-arguments":52467,"listData-memory-arguments":32,"mapData-cpu-arguments":64832,"mapData-memory-arguments":32,"mkCons-cpu-arguments":65493,"mkCons-memory-arguments":32,"mkNilData-cpu-arguments":22558,"mkNilData-memory-arguments":32,"mkNilPairData-cpu-arguments":16563,"mkNilPairData-memory-arguments":32,"mkPairData-cpu-arguments":76511,"mkPairData-memory-arguments":32,"modInteger-cpu-arguments-constant":196500,"modInteger-cpu-arguments-model-arguments-intercept":453240,"modInteger-cpu-arguments-model-arguments-slope":220,"modInteger-memory-arguments-intercept":0,"modInteger-memory-arguments-minimum":1,"modInteger-memory-arguments-slope":1,"multiplyInteger-cpu-arguments-intercept":69522,"multiplyInteger-cpu-arguments-slope":11687,"multiplyInteger-memory-arguments-intercept":0,"multiplyInteger-memory-arguments-slope":1,"nullList-cpu-arguments":60091,"nullList-memory-arguments":32,"quotientInteger-cpu-arguments-constant":196500,"quotientInteger-cpu-arguments-model-arguments-intercept":453240,"quotientInteger-cpu-arguments-model-arguments-slope":220,"quotientInteger-memory-arguments-intercept":0,"quotientInteger-memory-arguments-minimum":1,"quotientInteger-memory-arguments-slope":1,"remainderInteger-cpu-arguments-constant":196500,"remainderInteger-cpu-arguments-model-arguments-intercept":453240,"remainderInteger-cpu-arguments-model-arguments-slope":220,"remainderInteger-memory-arguments-intercept":0,"remainderInteger-memory-arguments-minimum":1,"remainderInteger-memory-arguments-slope":1,"serialiseData-cpu-arguments-intercept":1159724,"serialiseData-cpu-arguments-slope":392670,"serialiseData-memory-arguments-intercept":0,"serialiseData-memory-arguments-slope":2,"sha2_256-cpu-arguments-intercept":806990,"sha2_256-cpu-arguments-slope":30482,"sha2_256-memory-arguments":4,"sha3_256-cpu-arguments-intercept":1927926,"sha3_256-cpu-arguments-slope":82523,"sha3_256-memory-arguments":4,"sliceByteString-cpu-arguments-intercept":265318,"sliceByteString-cpu-arguments-slope":0,"sliceByteString-memory-arguments-intercept":4,"sliceByteString-memory-arguments-slope":0,"sndPair-cpu-arguments":85931,"sndPair-memory-arguments":32,"subtractInteger-cpu-arguments-intercept":205665,"subtractInteger-cpu-arguments-slope":812,"subtractInteger-memory-arguments-intercept":1,"subtractInteger-memory-arguments-slope":1,"tailList-cpu-arguments":41182,"tailList-memory-arguments":32,"trace-cpu-arguments":212342,"trace-memory-arguments":32,"unBData-cpu-arguments":31220,"unBData-memory-arguments":32,"unConstrData-cpu-arguments":32696,"unConstrData-memory-arguments":32,"unIData-cpu-arguments":43357,"unIData-memory-arguments":32,"unListData-cpu-arguments":32247,"unListData-memory-arguments":32,"unMapData-cpu-arguments":38314,"unMapData-memory-arguments":32,"verifyEcdsaSecp256k1Signature-cpu-arguments":20000000000,"verifyEcdsaSecp256k1Signature-memory-arguments":20000000000,"verifyEd25519Signature-cpu-arguments-intercept":9462713,"verifyEd25519Signature-cpu-arguments-slope":1021,"verifyEd25519Signature-memory-arguments":10,"verifySchnorrSecp256k1Signature-cpu-arguments-intercept":20000000000,"verifySchnorrSecp256k1Signature-cpu-arguments-slope":0,"verifySchnorrSecp256k1Signature-memory-arguments":20000000000}},"prices":{"memory":"577/10000","steps":"721/10000000"},"maxExecutionUnitsPerTransaction":{"memory":16000000,"steps":10000000000},"maxExecutionUnitsPerBlock":{"memory":80000000,"steps":40000000000},"maxValueSize":5000,"collateralPercentage":150,"maxCollateralInputs":3},"reflection":"Query-2nsxctnl7rgpuax"}
[ERROR] 2022-09-07T10:13:09.255Z Error when executing contract: Error: (AtKey "costModels" (AtKey "plutus:v1" (AtKey "addInteger-cpu-arguments-intercept" (TypeMismatch "Int"))))
    at Object.exports.error (/home/ubuntu/liqwid-offchain/cli.js:5339:12)
    at dispatchErrorToError (/home/ubuntu/liqwid-offchain/cli.js:27100:35)
    at /home/ubuntu/liqwid-offchain/cli.js:6032:51
    at __do (/home/ubuntu/liqwid-offchain/cli.js:27127:132)
    at __do (/home/ubuntu/liqwid-offchain/cli.js:27297:80)
    at func (/home/ubuntu/liqwid-offchain/cli.js:22820:14)
    at ReconnectingWebSocket._callEventListener (/home/ubuntu/liqwid-offchain/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:557:13)
    at /home/ubuntu/liqwid-offchain/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:81
    at Array.forEach (<anonymous>)
    at NoPerMessageDeflateWebSocket.ReconnectingWebSocket._handleMessage (/home/ubuntu/liqwid-offchain/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:38)
[INFO] 2022-09-07T10:13:09.255Z Retrying..
[DEBUG] 2022-09-07T10:13:09.256Z sending: {"args":{"query":{"utxo":["\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"]}},"methodname":"Query","mirror":"Query-2nsxctnl7rgpurs","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}
[DEBUG] 2022-09-07T10:13:09.257Z message: {"type":"jsonwsp/fault","version":"1.0","servicename":"ogmios","fault":{"code":"client","string":"Invalid request: invalid query."},"reflection":"Query-2nsxctnl7rgpurs"}
```

**Comment by uhbif19** [comment]
@klntsky So, as I understand, main issue #875 got fixed and this should be fixed too?

**Comment by klntsky** [comment]
It must be due to OOM in WASM allocations.

https://github.com/Plutonomicon/cardano-transaction-lib/issues/102

We need to confirm this. If so, the fix is scheduled in v5, but will actually be available to use anytime before, depending on our priorities.

How to confirm:

1. Write some code that touches CSL serialization/deserialization
2. Execute it in a loop for some unreasonable number of times
3. Wait for it to throw

E.g.


```
const res = [];
while (true) {
    const x = new Uint8Array(Array(10000000).fill(0));
    const b = lib.PlutusData.new_bytes(x);
    res.push(b);
}
```

As a workaround that can improve the situation, make sure you don't re-parse ProtocolParameters too often, because that's where a lot of CSL objects leak.

**Comment by klntsky** [comment]
Closing. We added GC to CSL
