### ISSUE TITLE
Non-determinism in balancer [Meta-task]

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1174]
We have some sort of non-determinism in the balancer (?) that leads to errors, but only sometimes.
 
Let's use this issue to collect failing logs that hopefully can help us pin down the issue eventually.

Grouped by type of error:

## `submit call failed. Error from Ogmios: [{"valueNotConserved...`

[log1.txt](https://github.com/Plutonomicon/cardano-transaction-lib/files/9923666/log1.txt)
[commit](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1170/commits/9f6a0becf92c1c264306cb64570c64f1ebc43aa2), [PR](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1170#pullrequestreview-1165883048)

**Comment by uhbif19** [comment]
Looks like example of the last problem: https://ci.staging.mlabs.city/build/121841/nixlog/2

**Comment by jy14898** [comment]
submit call failed. Error from Ogmios: [{"valueNotConserved...
this time for `Evaluation with additional UTxOs`
https://ci.staging.mlabs.city/build/134166/log

makes sense

**Comment by klntsky** [comment]
I think the `valueNotConserved` + `badInputs` in `AdditionalUtxoSet*` tests happens because when we make two subsequent `submit` calls there's no guarantee that ogmios will see the outputs of the first transaction when we send the second one. We should probably ask upstream if it is possible to provide an additional UTxO set for submit endpoint as well, just like it is done for evaluteTx.

**Comment by uhbif19** [comment]
@klntsky 

https://github.com/Plutonomicon/cardano-transaction-lib/pull/1267 says it covers ClientHttpError case. If so it seems like this issue solved?

**Comment by klntsky** [comment]
@uhbif19 as it always is with race condition issues, _remains to be seen_.

**Comment by uhbif19** [comment]
@klntsky I mean the PR is merged for more than a week. And as far as I understand, ClientHttpError was quite frequent in CIs. So if there was no fails for last days, then bug is fixed, no?

**Comment by Luis-omega** [comment]
I think I got the insights of this error:

```
  ✗ gero:http://localhost:4008/?gero:ECDSA:

  Error: Error: (TxOutRefWrongType (TransactionInput { index: 0u, transactionId: (TransactionHash (hexToByteArrayUnsafe "3ca8852ff76537383dded28f3d65249b76b605890193ee306f7e0584b2e5d19a")) }))
    at exports.error (webpack-internal:///./output.js:2367:12)
    at Object.$$throw [as throw] (webpack-internal:///./output.js:2415:47)
    at eval (webpack-internal:///./output.js:33552:47)
    at eval (webpack-internal:///./output.js:2215:26)
    at eval (webpack-internal:///./output.js:9248:36)
    at run (webpack-internal:///./output.js:11927:24)
    at eval (webpack-internal:///./output.js:11997:21)
    at drain (webpack-internal:///./output.js:11769:11)
    at Object.enqueue (webpack-internal:///./output.js:11790:13)
    at eval (webpack-internal:///./output.js:11988:29)
```

in this pr : #1326 

Basically, the failure on eternl made it an error that always happens in one of the commits from the beginning, which allow me to trace the error.

Basically, the test,
- first locks some value behind a script
-  get the full array of utxos locked at that script 
- keep the first utxo 
-attempt to expend the outxo

 That means sometimes the chosen utxo wasn't the one we performed, this was solved by passing to the second stage of the script the has of the transaction we expect to consume and look for it.

Currently this make the test to bypass this error but broke the assertions.
