### ISSUE TITLE
Cleanup race condition with rmdirSync

### ISSUE THREAD

**Issue by Geometer1729** [Plutonomicon/cardano-transaction-lib#1229]
Tests sometimes throw
```
Error: ENOENT: no such file or directory, stat '/build/test-cluster29'
    at Object.statSync (node:fs:1538:3)
    at __node_internal_ (node:internal/fs/utils:793:8)
    at Object.rmdirSync (node:fs:1156:15)
    at /nix/store/9vxqdmxsri53q0bginxacl85rr27a43r-Test.Main-compiled/Ctl.Internal.Plutip.Spawn/foreign.js:9:39
    at __do (/nix/store/9vxqdmxsri53q0bginxacl85rr27a43r-Test.Main-compiled/Ctl.Internal.Plutip.Spawn/index.js:148:63)
    at process.<anonymous> (/nix/store/9vxqdmxsri53q0bginxacl85rr27a43r-Test.Main-compiled/Node.Process/foreign.js:14:21)
    at process.emit (node:events:532:35) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/build/test-cluster29'
}
```
It seems to be a race condition with deleting the files here:
https://github.com/Plutonomicon/cardano-transaction-lib/blob/3789e92242c925523c02cad6b21a880490feba49/src/Internal/Plutip/Spawn.purs#L122-L132

The error should be safe to just ignore.

**Comment by pb99u069** [comment]
This problem should be fixed with [#1201](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1201), where we don't clean up `testClusterDir` anymore which gets already removed from the plutip side

**Comment by Geometer1729** [comment]
This seems to work downstream :+1:
