### ISSUE TITLE
cardano-serialisation-lib runtime error

### ISSUE THREAD

**Issue by sarkologist** [Plutonomicon/cardano-transaction-lib#1431]
in js console of browser app:
```
Uncaught (in promise) TypeError: TextDecoder is not a constructor
    at eval (cardano_serialization_lib.js?b43f:26:1)
    at ./node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js (vendors-node_modules_emurgo_cardano-message-signing-nodejs_cardano_message_signing_js-node_mo-d9bef1.bundle.js:27:1)
    at __webpack_require__ (bundle.js:676:32)
    at fn (bundle.js:939:20)
    at eval (output.js?ee2e:12801:11)
    at eval (output.js?ee2e:12913:2)
    at ./output.js (node_modules_emurgo_cardano-serialization-lib-nodejs_sync_recursive-output_js.bundle.js:35:1)
    at __webpack_require__ (bundle.js:676:32)
    at fn (bundle.js:939:20)
    at __webpack_require__.t (bundle.js:722:37)
```

`spago bundle-module -m Main --to output.js` and `webpack-dev-server --progress -o ./dist` compile fine

package.json:
```
 "dependencies": {
...
    "@emurgo/cardano-serialization-lib-browser": "11.2.1",
    "@emurgo/cardano-serialization-lib-nodejs": "11.2.1",
```

packages.dhall
```
        , repo = "https://github.com/Plutonomicon/cardano-transaction-lib.git"
        , version = "27f997461fda4a6f7eb52f1165a91d7d453fb990"
        }
```

**Comment by klntsky** [comment]
serialization-lib has nothing to do with this. When compiling to the browser, you have to set `BROWSER_RUNTIME=1`, but for node it must not be set.

These lines are self-explanatory: https://github.com/Plutonomicon/cardano-transaction-lib/blob/dca1003065ed96c7a37a8e34d8a348913bb56acb/src/Internal/Types/TokenName.js#L6

**Comment by klntsky** [comment]
This allows the bundler to pick the correct version.

**Comment by mgajda** [comment]
Wow, that is difficult to figure out without arcane knowledge.

Thanks!

**Comment by sarkologist** [comment]
@klntsky thanks! `BROWSER_RUNTIME=1` made it work 👍

**Comment by klntsky** [comment]
@mgajda it's all documented here: https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/ctl-as-dependency.md#using-ctl-from-js
