### ISSUE TITLE
Implement `utxosAt` for `KeyWallet`

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#617]
`utxosAt` does not work for `KeyWallet` for now, ~~because there's no algorithm for choosing collateral (while normal wallets provide `getCollateral`).~~ apparently for no reason.

Technically we can make `utxosAt` work without filtering a collateral right now, by replacing `KeyWallet _ -> pure Nothing` with `KeyWallet _ -> allUtxosAt address` in `QueryM.Utxos`. Since `selectCollateral` seems to be implemented already, we can try filtering it out to make balancing work similarly to browser wallets.

**Comment by Geometer1729** [comment]
I can't find a commit where `Error: (AtKey "SubmitSuccess" MissingValue)` is fixed and 

```

/home/bbrian/Code/mlabs/ardana/cardano-transaction-lib/output/Types.BigNum/foreign.js:14
exports.one = lib.BigNum.one();
                         ^

TypeError: lib.BigNum.one is not a function
    at Object.<anonymous> (/home/bbrian/Code/mlabs/ardana/cardano-transaction-lib/output/Types.BigNum/foreign.js:14:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/bbrian/Code/mlabs/ardana/cardano-transaction-lib/output/Types.BigNum/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[error] Tests failed: exit code: 1

```

hasn't been introduced. But I am able to get to the `Error: (AtKey "SubmitSuccess" MissingValue)` error with a KeyWallet now so I'm pretty sure this fix does work.
