### ISSUE TITLE
`feeTooSmall` error when `mustBeSignedBy` not used

### ISSUE THREAD

**Issue by rynoV** [Plutonomicon/cardano-transaction-lib#853]
See [here](https://github.com/Plutonomicon/cardano-transaction-lib/blob/b12c202ee162d18cb0a604cc445e8944238c0b58/src/Plutip/Types.purs#L319). When the `mustBeSignedBy` is not included, the following error is thrown when submitting the tx:

```
Error: `submit` call failed. Error from Ogmios: [{"feeTooSmall":{"actualFee":146700,"requiredFee":156800}}]
    at Object.exports.error (/home/calum/code/mlabs/seabug/seabug-contracts/output/Effect.Exception/foreign.js:8:10)
    at Object.$$throw [as throw] (/home/calum/code/mlabs/seabug/seabug-contracts/output/Effect.Exception/index.js:18:45)
    at /home/calum/code/mlabs/seabug/seabug-contracts/output/Contract.Transaction/index.js:139:105
    at /home/calum/code/mlabs/seabug/seabug-contracts/output/Control.Monad.Reader.Trans/index.js:108:34
    at run (/home/calum/code/mlabs/seabug/seabug-contracts/output/Effect.Aff/foreign.js:278:22)
    at /home/calum/code/mlabs/seabug/seabug-contracts/output/Effect.Aff/foreign.js:348:19
    at drain (/home/calum/code/mlabs/seabug/seabug-contracts/output/Effect.Aff/foreign.js:120:9)
    at Object.enqueue (/home/calum/code/mlabs/seabug/seabug-contracts/output/Effect.Aff/foreign.js:141:11)
    at /home/calum/code/mlabs/seabug/seabug-contracts/output/Effect.Aff/foreign.js:339:27
    at __do (/home/calum/code/mlabs/seabug/seabug-contracts/output/QueryM/index.js:533:139)
```

Reproduce using this utxo distribution:

```purescript
( withStakeKey (wrap privateStakeKey)
          [ BigInt.fromInt 1_000_000_000
          , BigInt.fromInt 2_000_000_000
          ]
      ) /\
        [ BigInt.fromInt 2_000_000_000 ]
```

_Also see comment by @klntsky in https://github.com/Plutonomicon/cardano-transaction-lib/pull/838#discussion_r937631251_

**Comment by ngua** [comment]
This is intended behavior -- the number of expected signatures affects the fee calculation by adding the PKHs to `TxBody.requiredSigners`

**Comment by klntsky** [comment]
@ngua why then we don't use `mustPayToPubkey` in any of the plutip tests and still everything works?

**Comment by ngua** [comment]
Because we're only signing it once. The code that @rynoV linked signs the tx twice
