### ISSUE TITLE
Investigate `MaxListenersExceededWarning` in nodejs

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#864]
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by epiro-ps** [comment]
Here's the log with `--trace-warnings`:
```
(node:685761) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:601:17)
    at process.addListener (node:events:619:10)
    at /nix/store/4f9s131s302588580cgn80ghrh9viqh6-Test.Main-compiled/Node.Process/foreign.js:13:13
    at __do (/nix/store/4f9s131s302588580cgn80ghrh9viqh6-Test.Main-compiled/Plutip.Spawn/index.js:99:11)
    at runSync (/nix/store/4f9s131s302588580cgn80ghrh9viqh6-Test.Main-compiled/Effect.Aff/foreign.js:90:20)
    at run (/nix/store/4f9s131s302588580cgn80ghrh9viqh6-Test.Main-compiled/Effect.Aff/foreign.js:328:22)
    at /nix/store/4f9s131s302588580cgn80ghrh9viqh6-Test.Main-compiled/Effect.Aff/foreign.js:348:19
    at drain (/nix/store/4f9s131s302588580cgn80ghrh9viqh6-Test.Main-compiled/Effect.Aff/foreign.js:120:9)
    at Object.enqueue (/nix/store/4f9s131s302588580cgn80ghrh9viqh6-Test.Main-compiled/Effect.Aff/foreign.js:141:11)
```

**Comment by klntsky** [comment]
This happens because we add global `process` `onExit` listeners in `Plutip.Spawn.killOnExit` for each child process.

We should instead add a single listener that reads a `Ref` containing all `ChildProcess`es to be killed, and maintain that `Ref` in `killOnExit`.

**Comment by klntsky** [comment]
We are OK with passing it around.

**Comment by jy14898** [comment]
The story has changed a little: we currently add exit handlers to clean up directories. This may be fixed with https://github.com/Plutonomicon/cardano-transaction-lib/pull/1201

**Comment by klntsky** [comment]
Does not happen anymore
