### ISSUE TITLE
Avoid using try/catch pattern in CSL bindings

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#875]
When switching `CostModel` from `Data.Int` to `Types.Int` (#874) I discovered that in case when we try to create too many `BigNum`s with `from_str` method unsuccessfully, at some point we start hitting memory access errors. 

To reproduce:

```
lib = require("@emurgo/cardano-serialization-lib-nodejs");

for (var i = 0; i < 100000; i++) {
    try {
        lib.BigNum.from_str('-1');
    } catch (e) {
        console.log(e);
    }
}

lib.BigNum.from_str('1');
```

Error example:

```
> lib.BigNum.from_str('1');
Uncaught RuntimeError: memory access out of bounds
    at <dlmalloc::sys::System as dlmalloc::Allocator>::alloc::h1d32aef92d923b70 (<anonymous>:wasm-function[3639]:0x13219d)
    at dlmalloc::dlmalloc::Dlmalloc<A>::malloc::h817d0bdbe748994d (<anonymous>:wasm-function[57]:0x2f15f)
    at dlmalloc::Dlmalloc<A>::malloc::h25d3e8a45fd7c029 (<anonymous>:wasm-function[631]:0xb2243)
    at __rdl_alloc (<anonymous>:wasm-function[4717]:0x13be80)
    at __rust_alloc (<anonymous>:wasm-function[4534]:0x13b4a6)
    at __wbindgen_malloc (<anonymous>:wasm-function[3825]:0x13496f)
    at passStringToWasm0 (/nix/store/dqg2a0mp8ra1zgscb7az11xhjpdr8ppa-node-dependencies-cardano-transaction-lib-2.0.0-alpha/lib/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:79:15)
    at Function.from_str (/nix/store/dqg2a0mp8ra1zgscb7az11xhjpdr8ppa-node-dependencies-cardano-transaction-lib-2.0.0-alpha/lib/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:1437:20)

```

The same happens in CTL [here](https://github.com/Plutonomicon/cardano-transaction-lib/blob/6cdbad6e3250101ac909c582be743c9ab2566d99/src/Types/BigNum.js#L34), because [here](https://github.com/Plutonomicon/cardano-transaction-lib/blob/6cdbad6e3250101ac909c582be743c9ab2566d99/src/Types/Int.purs#L42) we in fact rely on try/catch.

This is apparently triggered by https://github.com/Emurgo/cardano-serialization-lib/issues/151 which points to https://github.com/rustwasm/wasm-bindgen/issues/1963

**Comment by jy14898** [comment]
I'm quite surprised CSL hasn't upgraded for the proper fix via wasm-bindgen. It's very much a code smell and not the right solution (imo) for us to be asking for permission rather than forgiveness for CSL methods. https://github.com/Emurgo/cardano-serialization-lib/issues/362 tracks the upgrade, looks like it's not got any movement at the moment however

**Comment by jy14898** [comment]
> I did have an idea of how we can test specifically for memory leaks: allocate something (BigNum is fine) and access the internal pointer, run the test, and allocate again and check the distance between the pointers. Might be fickle though, depends on how malloc is implemented in CSL.

https://github.com/Plutonomicon/cardano-transaction-lib/pull/1025#pullrequestreview-1131489364

**Comment by klntsky** [comment]
There are a few places left.
