### ISSUE TITLE
Plutip: fix `psql: server closed the connection unexpectedly`

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#934]
```
Error: Command failed: psql -h 127.0.0.1 -p 5433 -d postgres
psql: error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at /nix/store/blib5lc6glrrn11gmr86v64bbrv2d8m9-cardano-transaction-lib/output/Node.ChildProcess/foreign.js:60:39
    at runSync (/nix/store/blib5lc6glrrn11gmr86v64bbrv2d8m9-cardano-transaction-lib/output/Effect.Aff/foreign.js:90:20)
    at run (/nix/store/blib5lc6glrrn11gmr86v64bbrv2d8m9-cardano-transaction-lib/output/Effect.Aff/foreign.js:328:22)
    at /nix/store/blib5lc6glrrn11gmr86v64bbrv2d8m9-cardano-transaction-lib/output/Effect.Aff/foreign.js:348:19
    at drain (/nix/store/blib5lc6glrrn11gmr86v64bbrv2d8m9-cardano-transaction-lib/output/Effect.Aff/foreign.js:120:9)
    at Object.enqueue (/nix/store/blib5lc6glrrn11gmr86v64bbrv2d8m9-cardano-transaction-lib/output/Effect.Aff/foreign.js:141:11)
    at Timeout._onTimeout (/nix/store/blib5lc6glrrn11gmr86v64bbrv2d8m9-cardano-transaction-lib/output/Effect.Aff/foreign.js:339:27)
    at listOnTimeout (internal/timers.js:557:17) {
```

**Comment by klntsky** [comment]
https://ci.staging.mlabs.city/build/242730/nixlog/1/tail

**Comment by klntsky** [comment]
We now retry the first attempt
